@echo off
rem Validation-only work on this laptop, in two parts. Finished steps leave a marker in logs\done\,
rem so running the same command again skips them (a step that was interrupted starts again).
rem Do not edit this file while it is running: cmd reads it from disk step by step.
rem
rem   run_validation_grid_laptop.cmd           part 1, about 6.5 h:
rem       1. student tuning (decision D2)        ~40 min
rem       2. Track A start 11 (tuned settings)   ~50 min, reuses Teachers A and B
rem       3. Track A start 24                    ~2.5 h
rem       4. Track A start 37                    ~2.5 h
rem   run_shortcut_laptop.cmd                  part 2, about 5 h: shortcut experiment
rem
rem Nothing here touches the test windows. Full console log: logs\validation_grid_laptop.log
cd /d "%~dp0"
set PY=C:\venvs\kd-traffic\Scripts\python.exe
set PILOT=results\pilot\20260916-122627_S_train11-14
set TEACHER_B=results\track_a\20260916-140053_S_train11-14\models\teacherB_wide.pt
set LOG=logs\validation_grid_laptop.log
set DONE=logs\done
if not exist %DONE% mkdir %DONE%

echo ===== Part 1 started %date% %time% >> %LOG%
echo Part 1 running. Keep the laptop plugged in, lid open, and do not click inside this window.
echo Progress: %LOG%
call :step tuning "%PY% scripts\09_tune_students.py --size S --teachers-from %PILOT% --workers 0 --epoch-check" || goto :failed
call :step start11 "%PY% scripts\06_track_a.py --size S --start 11 --teachers-from %PILOT% --teacher-b-from %TEACHER_B% --workers 0" || goto :failed
call :step start24 "%PY% scripts\06_track_a.py --size S --start 24 --workers 0" || goto :failed
call :step start37 "%PY% scripts\06_track_a.py --size S --start 37 --workers 0" || goto :failed
echo ===== Part 1 finished %date% %time% >> %LOG%
echo Part 1 done. Tell Claude "done". Part 2 later: run_shortcut_laptop.cmd
pause
exit /b 0

:step
rem %1 = step name, %2 = command
if exist %DONE%\%~1.flag (
  echo [%~1] already done, skipped
  exit /b 0
)
echo [%~1] started %time%
echo ===== %~1 started %date% %time% >> %LOG%
%~2 >> %LOG% 2>&1 || exit /b 1
echo done > %DONE%\%~1.flag
echo [%~1] finished %time%
exit /b 0

:failed
echo ===== FAILED %date% %time% >> %LOG%
echo A step failed or was stopped. Running this command again resumes from that step.
echo If it failed on its own, tell Claude; the details are at the end of %LOG%.
pause
exit /b 1
