"""Known / unknown service lists shared by all experiments (generated by scripts/03_make_splits.py)."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Splits:
    known: list[str]
    val_unknown_near: list[str]
    val_unknown_far: list[str]
    test_unknown_near: list[str]
    test_unknown_far: list[str]
    disabled: list[str]
    categories: dict[str, str]
    digest: str = ""

    @property
    def val_unknown(self) -> list[str]:
        return self.val_unknown_near + self.val_unknown_far

    @property
    def test_unknown(self) -> list[str]:
        return self.test_unknown_near + self.test_unknown_far

    def groups(self) -> dict[str, list[str]]:
        return {
            "known": self.known,
            "val_unknown_near": self.val_unknown_near,
            "val_unknown_far": self.val_unknown_far,
            "test_unknown_near": self.test_unknown_near,
            "test_unknown_far": self.test_unknown_far,
            "disabled": self.disabled,
        }

    def validate(self, available: list[str] | None = None) -> None:
        """Check the rules of the split; with `available`, also check coverage of the dataset's services."""
        owner: dict[str, str] = {}
        for group, services in self.groups().items():
            for service in services:
                if service in owner:
                    raise ValueError(f"Service {service!r} is in both {owner[service]} and {group}")
                owner[service] = group
        if not self.known:
            raise ValueError("No known services")
        known_categories = {self.categories[s] for s in self.known}
        for service in self.val_unknown_near + self.test_unknown_near:
            if self.categories[service] not in known_categories:
                raise ValueError(f"Near unknown {service!r} has no known service in its category")
        for service in self.val_unknown_far + self.test_unknown_far:
            if self.categories[service] in known_categories:
                raise ValueError(f"Far unknown {service!r} shares a category with a known service")
        if available is not None:
            extra = sorted(set(owner) - set(available))
            missing = sorted(set(available) - set(owner))
            if extra:
                raise ValueError(f"Services not in the dataset: {extra}")
            if missing:
                raise ValueError(f"Dataset services not assigned to any group: {missing}")


def load_splits(path: Path) -> Splits:
    raw_bytes = Path(path).read_bytes()
    raw = json.loads(raw_bytes)
    splits = Splits(
        known=raw["known"],
        val_unknown_near=raw["val_unknown"]["near"],
        val_unknown_far=raw["val_unknown"]["far"],
        test_unknown_near=raw["test_unknown"]["near"],
        test_unknown_far=raw["test_unknown"]["far"],
        disabled=raw["disabled"],
        categories=raw["categories"],
        digest=hashlib.sha1(raw_bytes).hexdigest()[:12],
    )
    splits.validate()
    return splits
